version: "3.3"
services:
  web:
    container_name: core-web
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis
      - rabbitmq
    environment:
      RABBIT_DSM: amqp://user:password@rabbitmq/
      REDIS_DSN: redis://redis:6379
    ports:
      - '8022:80'

  redis:
    container_name: redis
    image: redis/redis-stack-server:latest
    restart: always
    ports:
      - '6379:6379'


  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    restart: always
    ports:
      - '15672:15672'
      - '5672:5672'

    healthcheck:
      test: [ "uvicorn", "app.api:app", "--host", "0.0.0.0", "--port", "80"]
      interval: 30s
      timeout: 10s
      retries: 5

    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password